rules:
  idiomatic:
    no-defined-entrypoint:
      # This repo consists of a set of library functions, which therefore have no entrypoint.
      level: ignore
  style:
    line-length:
      # This repo consists of references to deeply-nested data variables.
      level: ignore
